plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - offline
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      seed: true
      migrate: true
    seed:
      domain:
        sources:
          - table: testTable
            sources: [./.dynamodb/seed/testTable.json]

resources:
  Resources:
    testTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: testTable
        AttributeDefinitions:
          - AttributeName: param1
            AttributeType: S
        KeySchema:
          - AttributeName: param1
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
