service: sqs

plugins:
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: "2012-11-05"
    endpoint: http://0.0.0.0:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}

functions:
  receiver:
    handler: ./receiver.default
    events:
      - sqs: arn:aws:sqs:us-east-1:XXXXXX:testQueue

  sender:
    handler: ./sender.default

resources:
  Resources:
    MyFourthQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: testQueue
