service: dynamo

plugins: ${file(./plugins.yml):plugins-${self:provider.stage}}

custom: ${file(./custom.yml):custom-${self:provider.stage}}

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  environment:
    TABLE_NAME: testTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - !Join
          - ":"
          - - arn:aws:dynamodb
            - !Ref "AWS::Region"
            - !Ref "AWS::AccountId"
            - "testTable"

resources: ${file(./resources.yml):resources-${self:provider.stage}}

functions:
  function:
    handler: ./function.default
    events:
      - http:
          path: /
          method: get
